### ISSUE TITLE
Logout bug in Aisle section

### ISSUE THREAD

**Issue by dpham123** [MarkeyMarke/cmpe133-proj#16]
Clicking the logout button in the aisle section will not update the cart.
![Screen_Shot_2019-04-10_at_11 00 57_PM](https://user-images.githubusercontent.com/36905285/55934507-a4152b80-5be5-11e9-9dce-5946295f6767.png)

**Comment by dpham123** [comment]
Mark's solution: Francis would need to make a function that removes all items from the cart and then Atul would need to call that function too when logging out

**Comment by francis-sjsu123** [comment]
I added a clear cart function in app.js file. Atul just pass that as a props to whatever component you need it for. Its on the branch clearCart_function.

**Comment by atulmi** [comment]
Alright I called clearCart() in navbar.jsx upon the logout button being clicked. I tested it and the cart is now cleared out upon logout. Pushed my changes.
