### ISSUE TITLE
OnAuthStateChanged not updating cart

### ISSUE THREAD

**Issue by MarkeyMarke** [MarkeyMarke/cmpe133-proj#27]
https://github.com/MarkeyMarke/cmpe133-proj/blob/7fe73a5752662d308ab075881f8c2dbe0ba24293/src/App.js#L93

I'm opening up this issue so we can talk about it right here or on Discord. I have a few ideas to potentially get around this. According to this post: https://stackoverflow.com/questions/37873608/how-do-i-detect-if-a-user-is-already-logged-in-firebase it seems that using `var user = firebase.auth().currentUser;` from our `getUID()` function inside `firebase.auth().onAuthStateChanged(...)` may be a problem. This is because there are probably synchronization issues with doing this. What we could so is that outside of onAuthStateChanged we can just use `getUID()`, and then check if it's null or not. If it's not null, then we can proceed and set the cart accordingly.

If that doesn't work, then notice how onAuthStateChanged provides a user field in this line: https://github.com/MarkeyMarke/cmpe133-proj/blob/439105cda187089190bab733d62ed9db7ba2c698/src/App.js#L85 with that, perhaps instead of using getUID(), we can just get the user ID directly from that user reference as a property like `user.uid`, and then set the state using that uid instead.

**Comment by dpham123** [comment]
Closed because @atulmi fixed it
